virtualshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>',views.cart_remove,name='cart_remove')
]

virtualshop/shop/urls.py
from . import views
from django.contrib import admin
from django.urls import path

app_name = 'shop'

urlpatterns = [
    path('', views.produto_list, name='produto_list'),
    path(
        '<slug:categoria_slug>/',
        views.produto_list,
        name='produto_list_por_categoria'
    ),
    path(
        '<int:id>/<slug:slug>/',
        views.produto_detalhe,
        name='produto_detalhe'
    ),
]

virtualshop/virtualshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from virtualshop.settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root = MEDIA_ROOT
    )

virtualshop/cart/models.py
from django.db import models

# Create your models here.

virtualshop/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Categoria(models.Model):
    nome = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['nome']
        indexes = [
            models.Index(fields=['nome']),
        ]
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.nome
    
    def get_absolute_url(self):
        return reverse(
            'shop:produto_list_por_categoria', args=[self.slug]
        )
        
class Produto(models.Model):
    categoria = models.ForeignKey(
        Categoria,
        related_name='produtos',
        on_delete=models.CASCADE
    )
    nome = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    imagem = models.ImageField(upload_to='produtos/%Y/%m/%d',blank=True)
    descricao = models.TextField(blank=True)
    preco = models.DecimalField(max_digits=10,decimal_places=2)
    disponivel = models.BooleanField(default=True)
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('shop:produto_detalhe', args=[self.id, self.slug])

class Meta:
    ordering = ['nome']
    indexes = [
        models.Index(fields=['id','slug']),
        models.Index(fields=['nome']),
        models.Index(fields=['-criado']),
    ]

    def __str__(self) -> str:
        return self.nome

virtualshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range (1, 10)]

class CartAddProductForm(forms.Form):
    quantity=forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

virtualshop/cart/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .forms import CartAddProductForm
from .cart import Cart
from django.views.decorators.http import require_POST
from shop.models import Produto

# Create your views here.

def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Produto, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override'],
        )
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Produto, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override':True}
        )
    return render(request, 'cart/detail.html', {'cart': cart})

def product_detail(request, id, slug):
    product = get_object_or_404(
        Produto, id=id, slug=slug, disponivel=True
    )
    cart_product_form = CartAddProductForm
    return render(
        request, 'shop/produto/detail.html',
        {'produto':product}, {'cart_product_form':cart_product_form}
    )

virtualshop/shop/views.py
from django.shortcuts import get_object_or_404, render

from cart.forms import CartAddProductForm
from .models import Categoria, Produto

# Create your views here.
def produto_list(request, categoria_slug=None):
    categoria = None
    categorias = Categoria.objects.all()
    produtos = Produto.objects.filter(disponivel=True)
    if categoria_slug:
        categoria = get_object_or_404(Categoria, slug = categoria_slug)
        produtos = produtos.filter(categoria = categoria)
    return render(
        request,
        'shop/produto/list.html',
        {
            'categoria': categoria,
            'categorias': categorias,
            'produtos': produtos
        }
    )

def produto_detalhe(request, id, slug):
    produto = get_object_or_404(
        Produto, id = id, slug = slug, disponivel = True
    )
    cart_product_form = CartAddProductForm
    return render(
        request,
        'shop/produto/detail.html',
        {'produto': produto},
        {'cart_product_form':cart_product_form}
    )

virtualshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}VirtualShop{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">VirtualShop</a>
    </div>
    <div id="subheader">
      <div class="cart">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            Seu carrinho:
            <a href="{% url 'cart:cart_detail' %}">
              {{ total_items }} item{{ total_items|pluralize }},
              ${{ cart.get_price_total }}
            </a>
          {% elif not order %}
            Seu carrinho está vázio.
          {% endif %}
        {% endwith %}
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

virtualshop/shop/templates/shop/produto/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
  {{ produto.nome }}
{% endblock %}
{% block content %}
  <div class="product-detail">
    <img src="{% if produto.imagem %}{{ produto.imagem.url }}{% else %}
    {% static 'img/no_image.png' %}{% endif %}">
    <h1>{{ produto.nome }}</h1>
    <h2>
      <a href="{{ produto.categoria.get_absolute_url }}">
        {{ produto.categoria }}
      </a>
    </h2>
    <p class="price">${{ produto.preco }}</p>
      <form action="{% url 'cart:cart_add' produto.id %}" method="post">
      {{ cart_produto_form }}
      {% csrf_token %}
      <input type="submit" value="Adicionar ao Carrinho">
    </form>
    {{ produto.descricao|linebreaks }}
  </div>
{% endblock %}

virtualshop/shop/templates/shop/produto/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% if categoria %}{{ categoria.name }}{% else %}Listagem de Produtos{% endif %}
{% endblock %}

{% block content %}
<div id='sidebar'>
  <h3>Categorias</h3>
  <ul>
    <li {% if not categoria %} class="selected" {% endif %}>
      <a href="{% url 'shop:produto_list' %}">Todas</a>
    </li>
    {% for c in categorias %}
    <li {% if categoria.slug is c.slug %} class="selected" {% endif %}>
      <a href="{{ c.get_absolute_url }}">{{ c.nome }}</a>
    </li>
    {% endfor %}
  </ul>
</div>
<div id="main" class="product-list">
  <h1>{% if categoria %}{{ categoria.nome }}{% else %}Produtos{% endif %}</h1>
  {% for produto in produtos %}
  <div class="item">
    <a href="{{ produto.get_absolute_url }}">
      <img src="{% if produto.imagem %}{{ produto.imagem.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
    </a>
    <a href="{{ produto.get_absolute_url }}">{{ produto.nome }}</a>
    <br>
    ${{ produto.preco }}
  </div>
  {% endfor %}
</div>
{% endblock %}